"""Native-launcher UI with cxtasks-style macOS glass material layers."""

from __future__ import annotations

import html
import json
from typing import Any

from . import __version__
from .config import AppConfig


def glass_alphas(transparency: float, dark: bool) -> tuple[float, float, float]:
    pane_floor = 0.25 if dark else 0.55
    sidebar_boost = 1.9 if dark else 1.6
    sidebar_floor = 0.10 if dark else 0.45
    pane = 1 - transparency * (1 - pane_floor)
    sidebar_t = min(1, transparency * sidebar_boost)
    sidebar = 1 - sidebar_t * (1 - sidebar_floor)
    surface = pane + (1 - pane) * 0.5
    return pane, sidebar, surface


def theme_settings(settings: dict[str, Any] | None) -> tuple[int, str]:
    """Clamp the persisted appearance settings to ``(glass_percent, theme)``."""
    glass = max(0, min(100, int((settings or {}).get("glass_transparency", 38))))
    theme = str((settings or {}).get("appearance_theme", "system"))
    if theme not in {"system", "light", "dark"}:
        theme = "system"
    return glass, theme


def theme_style(settings: dict[str, Any] | None) -> str:
    """The shared glass tokens, shell grid, sidebar, and nav rules.

    Every page that wants to look like the launcher (the vault shell included)
    starts its stylesheet with this block and overrides on top.
    """
    glass, _theme = theme_settings(settings)
    transparency = glass / 100
    light_pane, light_sidebar, light_surface = glass_alphas(transparency, False)
    dark_pane, dark_sidebar, dark_surface = glass_alphas(transparency, True)
    return f""":root{{--pane-alpha:{light_pane:.3f};--sidebar-alpha:{light_sidebar:.3f};--surface-alpha:{light_surface:.3f};--bg-primary:247 247 247;--bg-sidebar:255 255 255;--bg-surface:252 252 252;--bg-elevated:255 255 255;--bg-input:255 255 255;--ink:13 13 13;--secondary:93 93 93;--muted:143 143 143;--faint:175 175 175;--line:rgb(0 0 0/.10);--line-soft:rgb(0 0 0/.055);--accent:58 131 247;--accent-hover:44 103 197;--button-bg:13 13 13;--button-hover:47 47 47;--button-ink:255 255 255;--good:61 138 67;--bad:208 46 46;--warning:199 98 33;color-scheme:light dark}}
:root[data-theme="light"]{{color-scheme:light}} :root[data-theme="dark"]{{--pane-alpha:{dark_pane:.3f};--sidebar-alpha:{dark_sidebar:.3f};--surface-alpha:{dark_surface:.3f};--bg-primary:24 24 24;--bg-sidebar:42 43 43;--bg-surface:28 28 28;--bg-elevated:45 45 45;--bg-input:45 45 45;--ink:255 255 255;--secondary:205 205 205;--muted:175 175 175;--faint:143 143 143;--line:rgb(255 255 255/.15);--line-soft:rgb(255 255 255/.06);--button-bg:48 48 48;--button-hover:65 65 65;--button-ink:249 249 249;--good:83 181 89;--bad:255 133 131;--warning:241 162 117;color-scheme:dark}}
@media(prefers-color-scheme:dark){{:root:not([data-theme="light"]){{--pane-alpha:{dark_pane:.3f};--sidebar-alpha:{dark_sidebar:.3f};--surface-alpha:{dark_surface:.3f};--bg-primary:24 24 24;--bg-sidebar:42 43 43;--bg-surface:28 28 28;--bg-elevated:45 45 45;--bg-input:45 45 45;--ink:255 255 255;--secondary:205 205 205;--muted:175 175 175;--faint:143 143 143;--line:rgb(255 255 255/.15);--line-soft:rgb(255 255 255/.06);--button-bg:48 48 48;--button-hover:65 65 65;--button-ink:249 249 249;--good:83 181 89;--bad:255 133 131;--warning:241 162 117;color-scheme:dark}}}}
*{{box-sizing:border-box}} html,body{{min-height:100%;margin:0;background:transparent}} body{{color:rgb(var(--ink));font:13px/1.5 -apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text","Helvetica Neue",sans-serif;-webkit-font-smoothing:antialiased}}
body:not(.native)::before{{content:"";position:fixed;inset:0;z-index:-2;background:radial-gradient(circle at 15% 8%,#9ecbff 0,transparent 34%),radial-gradient(circle at 88% 18%,#d8bcff 0,transparent 31%),radial-gradient(circle at 54% 100%,#ffd6b8 0,transparent 38%),#dce4ee}} body.native::before{{display:none}}
button,input{{font:inherit}} button{{cursor:pointer}} .shell{{display:grid;grid-template-columns:210px minmax(0,1fr);min-height:100vh;background:transparent}}
aside{{position:sticky;top:0;height:100vh;padding:28px 15px;background:rgb(var(--bg-sidebar)/var(--sidebar-alpha));border-right:1px solid var(--line-soft);backdrop-filter:saturate(1.18)}}
.brand{{display:flex;gap:10px;align-items:center;margin:0 9px 32px;font-size:15px;font-weight:650}} .mark{{display:grid;place-items:center;width:29px;height:29px;border:1px solid rgb(255 255 255/.38);border-radius:9px;background:linear-gradient(145deg,rgb(var(--accent)/.95),rgb(var(--accent-hover)/.78));color:white;box-shadow:0 4px 14px rgb(var(--accent)/.24);font-size:15px}}
nav button{{display:block;width:100%;margin:2px 0;padding:8px 11px;border:0;border-radius:7px;background:transparent;color:rgb(var(--secondary));text-align:left;transition:background .12s,color .12s}} nav button:hover{{background:rgb(var(--ink)/.06);color:rgb(var(--ink))}} nav button.active{{background:rgb(var(--ink)/.09);color:rgb(var(--ink));font-weight:600}}
.aside-foot{{position:absolute;bottom:20px;left:25px;color:rgb(var(--faint));font-size:11px}} main{{min-width:0;padding:42px 46px 80px;background:rgb(var(--bg-primary)/var(--pane-alpha));backdrop-filter:saturate(1.12)}}
body.native aside{{padding-top:52px}} body.native main{{padding-top:62px}}
@media(prefers-reduced-transparency:reduce){{:root{{--pane-alpha:1!important;--sidebar-alpha:1!important;--surface-alpha:1!important}} .open-card,.panel,.card{{backdrop-filter:none}}}}"""


def launcher_page(config: AppConfig, settings: dict[str, Any] | None = None) -> str:
    token = json.dumps(config.token)
    default_folder = html.escape(str(config.default_folder), quote=True)
    version = html.escape(__version__)
    glass, theme = theme_settings(settings)
    shared_style = theme_style(settings)
    return f"""<!doctype html><html data-theme="{theme}"><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1"><title>Ask Widget</title>
<style>
{shared_style}
/* Leave popup buttons and their menus to WebKit/AppKit. Custom borders,
   backgrounds, and option rows make the closed control look native while the
   open menu behaves like an unrelated web popover. */
select{{width:100%;min-width:0;min-height:32px;font:-apple-system-body;-webkit-appearance:menulist;appearance:menulist;cursor:default}}
.view{{display:none;max-width:1060px;margin:auto}} .view.active{{display:block}} h1{{margin:0;font-size:29px;line-height:1.12;letter-spacing:-.035em}} .lead{{margin:7px 0 28px;color:rgb(var(--secondary));font-size:14px}} h2{{margin:34px 0 13px;font-size:15px}}
.open-card,.panel,.card{{border:1px solid var(--line-soft);background:rgb(var(--bg-surface)/var(--surface-alpha));box-shadow:inset 0 1px 0 rgb(255 255 255/.035),0 1px 2px rgb(0 0 0/.055)}} .open-card{{padding:23px;border-radius:14px}}
label{{display:block;margin:0 0 6px;color:rgb(var(--secondary));font-size:11px;font-weight:650}} .row{{display:flex;gap:8px}} input:not([type=checkbox]):not([type=range]){{width:100%;padding:9px 11px;border:1px solid var(--line);border-radius:8px;background:rgb(var(--bg-input)/.88);color:rgb(var(--ink));box-shadow:inset 0 1px 0 rgb(255 255 255/.025),0 1px 1px rgb(0 0 0/.025)}} input:not([type=checkbox]):not([type=range]):focus{{outline:2px solid rgb(var(--accent)/.26);outline-offset:0;border-color:rgb(var(--accent))}}
.field{{margin-bottom:14px}} .field-help{{margin:6px 1px 0;color:rgb(var(--muted));font-size:10.5px;line-height:1.4}} .field-help.ok{{color:rgb(var(--good))}} .field-help.bad{{color:rgb(var(--bad))}} .pick{{display:none;white-space:nowrap}} body.native .pick{{display:block}} .primary,.secondary,.danger{{padding:9px 14px;border-radius:8px;font-weight:600;transition:.12s}}
.primary{{border:1px solid transparent;background:rgb(var(--button-bg));color:rgb(var(--button-ink));box-shadow:0 1px 2px rgb(0 0 0/.12)}} .primary:hover{{background:rgb(var(--button-hover))}} .secondary{{border:1px solid var(--line-soft);background:rgb(var(--ink)/.055);color:rgb(var(--ink));box-shadow:inset 0 1px 0 rgb(255 255 255/.025)}} .secondary:hover{{border-color:var(--line);background:rgb(var(--ink)/.09)}} .primary:focus-visible,.secondary:focus-visible,.danger:focus-visible{{outline:1.5px solid rgb(var(--ink));outline-offset:2.5px}} .danger{{border:1px solid rgb(var(--bad)/.28);background:rgb(var(--bad)/.07);color:rgb(var(--bad))}}
.toolbar{{display:flex;align-items:center;gap:9px;margin-bottom:15px}} .toolbar input{{max-width:420px}} .toolbar>select{{width:auto;min-width:176px;max-width:280px}} .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(255px,1fr));gap:11px}} .card{{padding:15px;border-radius:11px;transition:transform .12s,border-color .12s,background .12s}} .card:hover{{transform:translateY(-1px);border-color:rgb(var(--accent)/.32);background:rgb(var(--bg-surface)/.98)}}
.card-title{{margin:0 0 4px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}} .meta{{color:rgb(var(--muted));font-size:11px}} .excerpt{{display:-webkit-box;margin:9px 0 0;overflow:hidden;color:rgb(var(--secondary));-webkit-line-clamp:3;-webkit-box-orient:vertical}} .card-actions{{display:flex;gap:10px;margin-top:12px}} .card-actions button,.card-actions a{{border:0;background:none;color:rgb(var(--accent));font-size:11px;text-decoration:none;padding:0}}
.history-toolbar{{display:grid;grid-template-columns:minmax(210px,2fr) repeat(4,minmax(115px,1fr));gap:9px;margin-bottom:15px}} .history-toolbar input,.history-toolbar select{{min-width:0}} .history-grid{{display:grid;gap:10px}} .history-card{{cursor:pointer;text-align:left}} .history-card:focus-visible{{outline:2px solid rgb(var(--accent));outline-offset:2px}} .history-head{{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}} .badges{{display:flex;gap:5px;flex-wrap:wrap}} .badge{{display:inline-flex;padding:2px 7px;border-radius:999px;background:rgb(var(--ink)/.065);color:rgb(var(--secondary));font-size:9px;font-weight:650;text-transform:uppercase;letter-spacing:.035em}} .badge.generated{{background:rgb(var(--good)/.12);color:rgb(var(--good))}} .badge.rerun,.badge.edited,.badge.continue{{background:rgb(var(--accent)/.13);color:rgb(var(--accent))}}
.history-dialog{{width:min(720px,calc(100vw - 42px));max-height:calc(100vh - 70px);padding:0;border:1px solid var(--line);border-radius:16px;background:rgb(var(--bg-elevated)/.94);color:rgb(var(--ink));box-shadow:0 28px 90px rgb(0 0 0/.32);backdrop-filter:blur(28px) saturate(1.2)}} .history-dialog::backdrop{{background:rgb(0 0 0/.34);backdrop-filter:blur(5px)}} .history-detail{{padding:24px}} .history-detail-head{{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}} .history-detail-head h2{{margin:0 0 5px;font-size:19px}} .icon-button{{border:0;border-radius:7px;background:transparent;color:rgb(var(--muted));font-size:20px;line-height:1;padding:5px 8px}} .icon-button:hover{{background:rgb(var(--ink)/.07);color:rgb(var(--ink))}} .history-block{{margin-top:18px}} .history-block h3{{margin:0 0 6px;color:rgb(var(--muted));font-size:10px;text-transform:uppercase;letter-spacing:.06em}} .history-block pre{{max-height:250px;margin:0;padding:13px;border:1px solid var(--line-soft);border-radius:9px;background:rgb(var(--ink)/.035);color:rgb(var(--ink));font:12px/1.55 -apple-system,BlinkMacSystemFont,"SF Pro Text",sans-serif;white-space:pre-wrap;overflow:auto}} .history-actions{{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}} .history-actions a{{text-decoration:none}}
.settings-grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}} .panel{{padding:21px;border-radius:12px}} .panel h2{{margin:0 0 17px}} .root{{display:flex;gap:8px;align-items:center;padding:9px 0;border-top:1px solid var(--line-soft)}} .root:first-child{{border-top:0}} .root code{{flex:1;overflow:hidden;text-overflow:ellipsis}} .status{{display:flex;gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line-soft)}} .status:last-child{{border-bottom:0}} .dot{{width:8px;height:8px;border-radius:50%;background:rgb(var(--faint));box-shadow:0 0 0 3px rgb(var(--faint)/.12)}} .dot.ok{{background:rgb(var(--good));box-shadow:0 0 0 3px rgb(var(--good)/.12)}} .dot.bad{{background:rgb(var(--bad));box-shadow:0 0 0 3px rgb(var(--bad)/.12)}}
.empty{{padding:27px;border:1px dashed var(--line);border-radius:11px;color:rgb(var(--muted));text-align:center}} .toast{{position:fixed;right:24px;bottom:24px;padding:10px 15px;border:1px solid rgb(255 255 255/.1);border-radius:9px;background:rgb(28 28 28/.9);backdrop-filter:blur(18px);color:#fff;box-shadow:0 10px 30px rgb(0 0 0/.2);opacity:0;transform:translateY(8px);transition:.2s;pointer-events:none}} .toast.show{{opacity:1;transform:none}}
.glass-scale{{display:flex;align-items:center;justify-content:space-between;margin-top:4px;color:rgb(var(--muted));font-size:10px}} .glass-scale strong{{color:rgb(var(--secondary));font-weight:600}} .cx-slider{{appearance:none;-webkit-appearance:none;height:20px;padding:0;border:0;background:transparent;box-shadow:none;cursor:grab}} .cx-slider::-webkit-slider-runnable-track{{height:4px;border-radius:2px;background:linear-gradient(to right,rgb(var(--accent)) 0%,rgb(var(--accent)) var(--fill,38%),rgb(var(--faint)/.35) var(--fill,38%),rgb(var(--faint)/.35) 100%)}} .cx-slider::-webkit-slider-thumb{{appearance:none;-webkit-appearance:none;width:14px;height:14px;margin-top:-5px;border:1px solid rgb(0 0 0/.08);border-radius:50%;background:#fff;box-shadow:0 1px 3px rgb(0 0 0/.4)}} .cx-slider:focus{{outline:none}}
@media(max-width:900px){{.history-toolbar{{grid-template-columns:repeat(2,minmax(0,1fr))}} .history-toolbar input{{grid-column:1/-1}}}} @media(max-width:800px){{.shell{{grid-template-columns:1fr}} aside{{position:static;height:auto;padding:12px 16px;background:rgb(var(--bg-sidebar)/.93)}} body.native aside{{padding:38px 16px 12px}} .brand{{margin:0 0 9px 2px}} nav{{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px}} nav button{{width:auto;margin:0;padding:7px 8px;text-align:center;white-space:nowrap}} .aside-foot{{display:none}} main,body.native main{{padding:28px 20px}} .settings-grid{{grid-template-columns:1fr}}}}
@media(max-width:560px){{nav{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}
</style></head><body><div class=shell><aside><div class=brand><span class=mark>✦</span>Ask Widget</div><nav>
<button class=active data-view=library>Library</button><button data-view=history>History</button><button data-href=/vault>Vault</button><button data-view=settings>Settings</button><button data-view=diagnostics>Diagnostics</button>
</nav><div class=aside-foot>v{version} · local-first</div></aside><main>
<section id=library class="view active"><h1>Your reading workspace</h1><p class=lead>Open a document, investigate a passage, and keep the useful answers.</p>
<div class=open-card><form id=open-form><div class=field><label for=source>Document URL or local file</label><div class=row><input id=source autofocus placeholder="HTML, Markdown, text, PDF, or https://…"><button class="secondary pick" type=button data-pick=file data-target=source>Choose…</button></div></div>
<div class=field><label for=folder>Context folder</label><div class=row><input id=folder value="{default_folder}"><button class="secondary pick" type=button data-pick=folder data-target=folder>Choose…</button></div><p class=field-help>Only files inside this folder are available to the selected provider as supporting evidence.</p></div><button class=primary>Open with Ask Widget</button></form></div>
<h2>Recent documents</h2><div class=toolbar><input id=search placeholder="Search documents and answers…"></div><div id=documents class=grid></div>
<h2>Recent answers</h2><div id=conversations class=grid></div></section>
<section id=history class=view><h1>Question history</h1><p class=lead>Find an earlier question, inspect its answer, or reuse it with the model you use now.</p>
<div class=history-toolbar><input id=history-search placeholder="Search questions, passages, and answers…"><select id=history-provider aria-label="Filter by provider"><option value="">All providers</option></select><select id=history-model aria-label="Filter by model"><option value="">All models</option></select><select id=history-document aria-label="Filter by document"><option value="">All documents</option></select><select id=history-date aria-label="Filter by date"><option value=0>Any time</option><option value=1>Today</option><option value=7>Past week</option><option value=30>Past month</option><option value=365>Past year</option></select></div>
<div class=toolbar><select id=history-action aria-label="Filter by question type"><option value="">All question types</option><option value=ask>Questions</option><option value=eli5>ELI5</option><option value=prove>Prove it</option></select><span id=history-count class=meta></span></div><div id=history-results class=history-grid></div></section>
<section id=settings class=view><h1>Settings</h1><p class=lead>Control appearance, models, retention, and trusted folders.</p><div class=settings-grid>
<form id=appearance-form class=panel><h2>Appearance</h2><div class=field><label for=appearance-theme>Color theme</label><select id=appearance-theme name=appearance_theme><option value=system>System</option><option value=light>Light</option><option value=dark>Dark</option></select></div><div class=field><label for=glass-transparency>Window transparency</label><input id=glass-transparency class=cx-slider name=glass_transparency type=range min=0 max=100 value="{glass}" style="--fill:{glass}%"><div class=glass-scale><span>Solid</span><strong id=glass-value>{glass}% glass</strong><span>Glass</span></div></div><div class=field><label><input name=markdown_follow_obsidian type=checkbox style="width:auto"> Match vault Markdown appearance</label><p id=markdown-theme-status class=field-help>Uses reading styles shared by the Ask Widget Obsidian plugin. Applies to Markdown notes only.</p></div><button class=primary>Save appearance</button></form>
<form id=settings-form class=panel><h2>Answers</h2><div class=field><label for=provider>Subscription provider</label><select id=provider name=provider><option value=claude>Claude</option><option value=codex>Codex</option></select><p id=provider-status class=field-help>Checking installed subscriptions…</p></div><div class=field><label id=model-label for=model>Model</label><select id=model><option>Loading models…</option></select><p id=model-help class=field-help></p></div><div class=field><label for=reasoning-effort>Reasoning effort</label><select id=reasoning-effort></select></div><div class=field><label for=response-style>Response style</label><select id=response-style name=response_style><option value=concise>Concise</option><option value=balanced>Balanced</option><option value=detailed>Detailed</option></select></div><div class=field><label for=first-activity>First activity timeout (seconds)</label><input id=first-activity name=first_activity_timeout type=number min=10 max=120></div><div class=field><label for=request-timeout>Total timeout (seconds)</label><input id=request-timeout name=request_timeout type=number min=30 max=600></div><button class=primary>Save settings</button></form>
<form id=privacy-form class=panel><h2>Storage and network</h2><div class=field><label for=cache-ttl>Answer cache lifetime (hours)</label><input id=cache-ttl name=cache_ttl_hours type=number min=0 max=8760></div><div class=field><label for=cache-max>Maximum cached answers</label><input id=cache-max name=cache_max_entries type=number min=0 max=1000></div><div class=field><label><input name=history_enabled type=checkbox style="width:auto"> Save reading history</label></div><div class=field><label><input name=allow_private_remote type=checkbox style="width:auto"> Allow trusted private-network URLs</label></div><button class=primary>Save settings</button></form>
<form id=vault-form class=panel><h2>Vault</h2><div class=field><label for=vault-root>Vault folder</label><div class=row><input id=vault-root name=vault_root placeholder="~/Documents/CX"><button class="secondary pick" type=button data-pick=folder data-target=vault-root>Choose…</button></div><p class=field-help>Browsed read-only in Vault. Saving also adds it to the allowed context roots so answers can cite your notes. Leave empty to hide Vault.</p></div><button class=primary>Save vault</button></form></div>
<h2>Allowed context roots</h2><div class=panel><div id=roots></div><button id=add-root class="secondary pick" type=button>Add folder…</button></div></section>
<section id=diagnostics class=view><h1>Diagnostics</h1><p class=lead>Verify both subscription runtimes before a reading session.</p><div class=toolbar><button id=refresh-diag class=secondary>Refresh</button><button id=probe class=primary>Probe selected provider</button></div><div id=diag class=panel>Loading…</div></section>
</main></div><dialog id=history-detail class=history-dialog><div class=history-detail><div class=history-detail-head><div><h2 id=history-detail-title>Saved answer</h2><div id=history-detail-meta class=meta></div></div><button id=history-detail-close class=icon-button aria-label="Close">×</button></div><div class=badges id=history-detail-badges></div><div class=history-block><h3>Passage</h3><pre id=history-detail-selection></pre></div><div class=history-block><h3>Question</h3><pre id=history-detail-question></pre></div><div class=history-block><h3>Answer</h3><pre id=history-detail-answer></pre></div><div id=history-detail-actions class=history-actions></div></div></dialog><div id=toast class=toast></div>
<script>
const TOKEN={token}; const INITIAL_GLASS={glass}; const INITIAL_THEME={json.dumps(theme)}; const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
let PROVIDERS={{}},CURRENT_SETTINGS={{}},HISTORY_ITEMS=new Map();
const native=!!(window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers.askwPick); if(native)document.body.classList.add('native');
const scheme=matchMedia('(prefers-color-scheme:dark)'); function isDark(){{const t=document.documentElement.dataset.theme;return t==='dark'||(t==='system'&&scheme.matches)}} function applyGlass(raw){{const t=Math.max(0,Math.min(1,Number(raw)/100));const dark=isDark();const pane=1-t*(1-(dark?.25:.55));const sidebarT=Math.min(1,t*(dark?1.9:1.6));const sidebar=1-sidebarT*(1-(dark?.10:.45));const surface=pane+(1-pane)*.5;const r=document.documentElement.style;r.setProperty('--pane-alpha',pane.toFixed(3));r.setProperty('--sidebar-alpha',sidebar.toFixed(3));r.setProperty('--surface-alpha',surface.toFixed(3));const slider=$('[name=glass_transparency]');if(slider){{slider.value=Math.round(t*100);slider.style.setProperty('--fill',Math.round(t*100)+'%')}}const out=$('#glass-value');if(out)out.textContent=Math.round(t*100)+'% glass'}} function applyTheme(raw){{const theme=['light','dark'].includes(raw)?raw:'system';document.documentElement.dataset.theme=theme;const picker=$('[name=appearance_theme]');if(picker)picker.value=theme;if(native&&window.webkit.messageHandlers.askwAppearance)window.webkit.messageHandlers.askwAppearance.postMessage({{theme}}).catch(()=>{{}});applyGlass($('[name=glass_transparency]')?.value??INITIAL_GLASS)}} scheme.addEventListener?.('change',()=>{{if(document.documentElement.dataset.theme==='system')applyGlass($('[name=glass_transparency]')?.value??INITIAL_GLASS)}}); applyTheme(INITIAL_THEME);
function toast(s){{const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2200)}}
async function api(url,opts={{}}){{const r=await fetch(url,opts);const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${{r.status}}`);return d}}
async function pick(kind,target){{const el=$('#'+target);const p=await window.webkit.messageHandlers.askwPick.postMessage({{kind,initial:el.value}});if(p)el.value=p}} document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>pick(b.dataset.pick,b.dataset.target));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{{if(b.dataset.href){{location.href=b.dataset.href;return}}document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='diagnostics')loadDiagnostics(false);if(b.dataset.view==='history')loadHistory()}}); if(location.hash){{const target=document.querySelector(`nav button[data-view="${{CSS.escape(location.hash.slice(1))}}"]`);if(target)target.click()}}
$('#open-form').onsubmit=e=>{{e.preventDefault();const s=$('#source').value.trim(),f=$('#folder').value.trim();if(!s)return;location.href='/view?src='+encodeURIComponent(s)+(f?'&folder='+encodeURIComponent(f):'')}};
function ago(ts){{const d=Math.max(0,Date.now()/1000-ts);if(d<60)return'just now';if(d<3600)return Math.floor(d/60)+'m ago';if(d<86400)return Math.floor(d/3600)+'h ago';return Math.floor(d/86400)+'d ago'}}
function modeLabel(c){{return({{generated:'Generated',rerun:'Asked again',edited:'Edited & asked',continue:'Continued'}})[c.request_mode]||'Generated'}}
function rememberHistory(items){{for(const item of items||[])HISTORY_ITEMS.set(item.request_id,item)}}
function historyCard(c){{return`<article class="card history-card" tabindex=0 data-history-id="${{esc(c.request_id)}}"><div class=history-head><div><p class=card-title>${{esc(c.document_title||c.action)}}</p><div class=meta>${{esc(c.provider||'claude')}} · ${{esc(c.model)}}${{c.effort?' · '+esc(c.effort):''}} · ${{ago(c.started_at)}}</div></div><span class="badge ${{esc(c.request_mode||'generated')}}">${{esc(modeLabel(c))}}</span></div><p class=excerpt>${{esc(c.question||c.action)}}</p><p class=excerpt>${{esc(c.answer||c.error||'No answer')}}</p></article>`}}
function wireHistoryCards(root){{document.querySelectorAll(root+' [data-history-id]').forEach(card=>{{card.onclick=()=>showHistory(card.dataset.historyId);card.onkeydown=e=>{{if(e.key==='Enter'||e.key===' '){{e.preventDefault();showHistory(card.dataset.historyId)}}}}}})}}
function renderLibrary(data){{const docs=data.documents||[],conv=data.conversations||[];rememberHistory(conv);$('#documents').innerHTML=docs.length?docs.map(d=>`<article class=card><p class=card-title title="${{esc(d.source)}}">${{esc(d.title)}}</p><div class=meta>${{esc(d.kind)}} · ${{d.conversation_count||0}} answers · ${{ago(d.last_opened_at)}}</div><div class=card-actions><a href="/view?src=${{encodeURIComponent(d.source)}}${{d.folder?'&folder='+encodeURIComponent(d.folder):''}}">Open</a><a href="/api/export?src=${{encodeURIComponent(d.source)}}">Export notes</a></div></article>`).join(''):'<div class=empty>Documents you open will appear here.</div>';$('#conversations').innerHTML=conv.length?conv.slice(0,12).map(historyCard).join(''):'<div class=empty>Your completed answers will be saved here.</div>';wireHistoryCards('#conversations')}}
async function loadLibrary(q=''){{try{{renderLibrary(await api('/api/library?q='+encodeURIComponent(q)))}}catch(e){{toast(e.message)}}}} let searchTimer;$('#search').oninput=e=>{{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadLibrary(e.target.value),180)}};
function setOptions(id,items,label,valueOf=x=>x,labelOf=x=>x){{const el=$(id),current=el.value;el.innerHTML=`<option value="">${{esc(label)}}</option>`+(items||[]).map(x=>`<option value="${{esc(valueOf(x))}}">${{esc(labelOf(x))}}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current}}
function applyHistoryFacets(f){{setOptions('#history-provider',f.providers,'All providers');setOptions('#history-model',f.models,'All models');setOptions('#history-document',f.documents,'All documents',x=>x.source,x=>x.title)}}
function renderHistory(data){{const items=data.conversations||[];rememberHistory(items);applyHistoryFacets(data.facets||{{providers:[],models:[],documents:[]}});$('#history-count').textContent=items.length+' saved '+(items.length===1?'answer':'answers');$('#history-results').innerHTML=items.length?items.map(historyCard).join(''):'<div class=empty>No saved answers match these filters.</div>';wireHistoryCards('#history-results')}}
async function loadHistory(){{const p=new URLSearchParams({{q:$('#history-search').value,provider:$('#history-provider').value,model:$('#history-model').value,source:$('#history-document').value,days:$('#history-date').value,action:$('#history-action').value}});try{{renderHistory(await api('/api/library?'+p))}}catch(e){{toast(e.message)}}}}
function readerUrl(item,action){{const p=new URLSearchParams(),selectionSource=String(item.document_source||'').startsWith('service://selection/');let base;if(selectionSource){{base='/quick';p.set('text',item.selection||'');if(item.folder)p.set('folder',item.folder)}}else{{base='/view';p.set('src',item.document_source||'');if(item.folder)p.set('folder',item.folder)}}if(action){{p.set('history',item.request_id);p.set('history_action',action)}}return base+'?'+p.toString()}}
async function showHistory(id){{try{{let item=HISTORY_ITEMS.get(id);if(!item){{const d=await api('/api/conversations/'+encodeURIComponent(id));item=d.conversation;HISTORY_ITEMS.set(id,item)}}$('#history-detail-title').textContent=item.document_title||'Saved answer';$('#history-detail-meta').textContent=new Date(item.started_at*1000).toLocaleString()+' · '+(item.provider||'claude')+' · '+item.model+(item.effort?' · '+item.effort:'')+(item.latency_ms?' · '+(item.latency_ms/1000).toFixed(1)+'s':'');$('#history-detail-badges').innerHTML=`<span class="badge ${{esc(item.request_mode||'generated')}}">${{esc(modeLabel(item))}}</span><span class=badge>${{esc(item.action)}}</span>`;$('#history-detail-selection').textContent=item.selection||'No saved passage';$('#history-detail-question').textContent=item.question||item.action;$('#history-detail-answer').textContent=item.answer||item.error||'No answer';$('#history-detail-actions').innerHTML=`<a class=primary href="${{esc(readerUrl(item,'rerun'))}}">Ask again</a><a class=secondary href="${{esc(readerUrl(item,'edited'))}}">Edit & ask</a><a class=secondary href="${{esc(readerUrl(item,'continue'))}}">Continue</a><a class=secondary href="${{esc(readerUrl(item,''))}}">Open document</a>`;$('#history-detail').showModal()}}catch(e){{toast(e.message)}}}}
$('#history-detail-close').onclick=()=>$('#history-detail').close();$('#history-detail').onclick=e=>{{if(e.target===$('#history-detail'))$('#history-detail').close()}};let historyTimer;$('#history-search').oninput=()=>{{clearTimeout(historyTimer);historyTimer=setTimeout(loadHistory,180)}};for(const id of ['history-provider','history-model','history-document','history-date','history-action'])$('#'+id).onchange=loadHistory;
function fillForm(form,s){{for(const e of form.elements)if(e.name&&s[e.name]!==undefined){{if(e.type==='checkbox')e.checked=!!s[e.name];else e.value=s[e.name]}}}}
function effortLabel(v){{return({{low:'Low',medium:'Medium',high:'High',xhigh:'Extra high',max:'Maximum',ultra:'Ultra'}})[v]||v}}
function renderEfforts(provider,catalog,model){{const field=$('#reasoning-effort'),info=(catalog.models||[]).find(x=>x.id===model)||{{}};let efforts=(info.efforts||[]).slice();const saved=CURRENT_SETTINGS[provider+'_effort']||catalog.selected_effort||info.default_effort||'medium';if(!efforts.length)efforts=[saved];if(!efforts.includes(saved))efforts.push(saved);field.name=provider+'_effort';field.innerHTML=efforts.map(v=>`<option value="${{esc(v)}}">${{esc(effortLabel(v))}}</option>`).join('');field.value=efforts.includes(saved)?saved:(info.default_effort||efforts[0]);field.onchange=()=>CURRENT_SETTINGS[field.name]=field.value}}
function renderProvider(provider){{const catalog=PROVIDERS[provider]||{{id:provider,label:provider,models:[]}},model=$('#model');CURRENT_SETTINGS.provider=provider;$('#provider').value=provider;$('#model-label').textContent=(catalog.label||provider)+' model';const status=$('#provider-status');status.className='field-help '+(catalog.subscription?'ok':'bad');status.textContent=catalog.subscription?`Using ${{provider==='claude'?(catalog.plan?catalog.label+' '+catalog.plan:catalog.label):'ChatGPT'}} subscription · no API key billing`:(catalog.repair||'Subscription login unavailable');let models=(catalog.models||[]).slice();const key=provider+'_model',saved=CURRENT_SETTINGS[key]||catalog.selected_model||'';if(!models.length&&saved)models=[{{id:saved,label:saved,description:'Saved selection; live catalog unavailable.'}}];model.name=key;model.innerHTML=models.length?models.map(x=>`<option value="${{esc(x.id)}}"${{x.unavailable?' disabled':''}}>${{esc(x.label||x.id)}}</option>`).join(''):'<option value="" disabled>No available models</option>';if(models.some(x=>x.id===saved&&!x.unavailable))model.value=saved;else if(models.length)model.value=models.find(x=>!x.unavailable)?.id||models[0].id;CURRENT_SETTINGS[key]=model.value;function describe(){{const item=models.find(x=>x.id===model.value)||{{}};$('#model-help').textContent=item.description||'Reported by the installed CLI model catalog.';renderEfforts(provider,catalog,model.value)}}model.onchange=()=>{{CURRENT_SETTINGS[key]=model.value;describe()}};describe()}}
async function loadMarkdownThemeStatus(){{try{{const d=await api('/api/markdown-theme');$('#markdown-theme-status').textContent=!d.enabled?'Using Ask Widget’s default Markdown styles.':d.available?'Following your vault’s reading styles. Updates automatically while Obsidian is open.':'Waiting for Obsidian. Enable the Ask Widget plugin in your configured vault to sync reading styles.'}}catch(e){{}}}}
async function loadSettings(){{const d=await api('/api/settings');CURRENT_SETTINGS=d.settings;fillForm($('#appearance-form'),d.settings);fillForm($('#settings-form'),d.settings);fillForm($('#privacy-form'),d.settings);fillForm($('#vault-form'),d.settings);applyTheme(d.settings.appearance_theme);loadMarkdownThemeStatus();try{{const catalogs=await api('/api/models');PROVIDERS=Object.fromEntries((catalogs.providers||[]).map(p=>[p.id,p]))}}catch(e){{PROVIDERS={{claude:{{id:'claude',label:'Claude',selected_model:d.settings.claude_model,models:[]}},codex:{{id:'codex',label:'Codex',selected_model:d.settings.codex_model,models:[]}}}};toast('Model catalog unavailable: '+e.message)}}renderProvider(d.settings.provider||'claude');$('#provider').onchange=e=>renderProvider(e.target.value);$('#roots').innerHTML=d.roots.map(r=>`<div class=root><code>${{esc(r.path)}}</code><span class=meta>${{r.builtin?'built in':''}}</span>${{r.builtin?'':`<button class=danger data-remove="${{esc(r.path)}}">Remove</button>`}}</div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeRoot(b.dataset.remove))}}
async function saveForm(form){{const body={{}};for(const e of form.elements)if(e.name)body[e.name]=e.type==='checkbox'?e.checked:(e.type==='number'||e.type==='range'?Number(e.value):e.value);await api('/api/settings',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{token:TOKEN,settings:body}})}});toast('Settings saved');await loadSettings()}}
for(const id of ['appearance-form','settings-form','privacy-form','vault-form'])$('#'+id).onsubmit=e=>{{e.preventDefault();saveForm(e.target).catch(x=>toast(x.message))}}; $('[name=glass_transparency]').oninput=e=>applyGlass(e.target.value); $('[name=appearance_theme]').onchange=e=>applyTheme(e.target.value);
$('#add-root').onclick=async()=>{{try{{const p=await window.webkit.messageHandlers.askwPick.postMessage({{kind:'folder',initial:''}});if(p){{await api('/api/roots',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{token:TOKEN,path:p}})}});await loadSettings();toast('Allowed root added')}}}}catch(e){{toast(e.message)}}}};
async function removeRoot(path){{try{{await api('/api/roots',{{method:'DELETE',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{token:TOKEN,path}})}});await loadSettings()}}catch(e){{toast(e.message)}}}}
function diagRow(name,ok,detail){{return`<div class=status><span class="dot ${{ok?'ok':'bad'}}"></span><div><strong>${{esc(name)}}</strong><div class=meta>${{esc(detail)}}</div></div></div>`}}
async function loadDiagnostics(probe){{$('#diag').textContent=probe?'Running a live subscription request…':'Checking…';try{{const d=await api('/api/diagnostics'+(probe?'?probe=1':'')),st=d.storage,selected=d.providers[d.selected_provider];let rows='';for(const id of ['claude','codex']){{const p=d.providers[id];rows+=diagRow(`${{p.label}} CLI`,p.installed,p.version||p.path||p.repair)+diagRow(`${{p.label}} subscription`,p.subscription,p.subscription?(id==='claude'?`${{p.plan||'active'}} plan`:'Signed in with ChatGPT'):(p.repair||p.auth_detail||'Not signed in'))}}rows+=diagRow('Selected runtime',selected.probe?selected.probe.ok:selected.ok,selected.probe?(selected.probe.ok?`${{d.selected_provider}}/${{d.selected_model}} passed in ${{selected.probe.latency_ms}}ms`:selected.probe.error):`${{d.selected_provider}}/${{d.selected_model}} · ${{d.selected_effort}} effort`)+diagRow('Reading database',st.ok,`${{st.documents}} documents · ${{st.conversations}} answers · schema ${{st.schema_version}}`)+diagRow('Default folder',d.folder.ok,d.folder.path);$('#diag').innerHTML=rows}}catch(e){{$('#diag').textContent=e.message}}}}
$('#refresh-diag').onclick=()=>loadDiagnostics(false);$('#probe').onclick=()=>loadDiagnostics(true); loadLibrary();loadSettings().catch(e=>toast(e.message));
</script></body></html>"""
